// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for CreateSessionRequestMode.
const (
	CreateSessionRequestModePool   CreateSessionRequestMode = "pool"
	CreateSessionRequestModeSticky CreateSessionRequestMode = "sticky"
)

// Valid indicates whether the value is a known member of the CreateSessionRequestMode enum.
func (e CreateSessionRequestMode) Valid() bool {
	switch e {
	case CreateSessionRequestModePool:
		return true
	case CreateSessionRequestModeSticky:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for SessionMode.
const (
	SessionModePool   SessionMode = "pool"
	SessionModeSticky SessionMode = "sticky"
)

// Valid indicates whether the value is a known member of the SessionMode enum.
func (e SessionMode) Valid() bool {
	switch e {
	case SessionModePool:
		return true
	case SessionModeSticky:
		return true
	default:
		return false
	}
}

// Defines values for SessionStatus.
const (
	SessionStatusFinished SessionStatus = "finished"
	SessionStatusRunning  SessionStatus = "running"
	SessionStatusStopped  SessionStatus = "stopped"
)

// Valid indicates whether the value is a known member of the SessionStatus enum.
func (e SessionStatus) Valid() bool {
	switch e {
	case SessionStatusFinished:
		return true
	case SessionStatusRunning:
		return true
	case SessionStatusStopped:
		return true
	default:
		return false
	}
}

// CreateSessionRequest defines model for CreateSessionRequest.
type CreateSessionRequest struct {
	CadenceSeconds     int                      `json:"cadence_seconds"`
	DialTimeoutMs      *int                     `json:"dial_timeout_ms,omitempty"`
	MaxDurationSeconds *int                     `json:"max_duration_seconds,omitempty"`
	MaxSamples         *int                     `json:"max_samples,omitempty"`
	Mode               CreateSessionRequestMode `json:"mode"`
	Name               string                   `json:"name"`
	ProbeTarget        *string                  `json:"probe_target,omitempty"`
	ProbesPerSample    *int                     `json:"probes_per_sample,omitempty"`
	Proxy              *string                  `json:"proxy,omitempty"`
}

// CreateSessionRequestMode defines model for CreateSessionRequest.Mode.
type CreateSessionRequestMode string

// Error defines model for Error.
type Error struct {
	Code    string `json:"code"`
	Message string `json:"message"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// Hold defines model for Hold.
type Hold struct {
	DurationSeconds int64     `json:"duration_seconds"`
	EndedAt         time.Time `json:"ended_at"`
	Ip              string    `json:"ip"`
	Samples         int64     `json:"samples"`
	StartedAt       time.Time `json:"started_at"`
}

// IPRow defines model for IPRow.
type IPRow struct {
	Asn            string    `json:"asn"`
	Category       string    `json:"category"`
	Country        string    `json:"country"`
	DnsblHits      []string  `json:"dnsbl_hits"`
	DnsblListed    bool      `json:"dnsbl_listed"`
	FirstSeen      time.Time `json:"first_seen"`
	GreynoiseClass string    `json:"greynoise_class"`
	HitCount       int64     `json:"hit_count"`
	Ip             string    `json:"ip"`
	Isp            string    `json:"isp"`
	LastSeen       time.Time `json:"last_seen"`
	RiskScore      *int      `json:"risk_score"`
}

// PoolComposition defines model for PoolComposition.
type PoolComposition struct {
	Datacenter  int `json:"datacenter"`
	Mobile      int `json:"mobile"`
	Residential int `json:"residential"`
	Unknown     int `json:"unknown"`
}

// PoolGrowthPoint defines model for PoolGrowthPoint.
type PoolGrowthPoint struct {
	At          time.Time `json:"at"`
	DistinctIps int64     `json:"distinct_ips"`
}

// Readiness defines model for Readiness.
type Readiness struct {
	Clickhouse bool `json:"clickhouse"`
	Postgres   bool `json:"postgres"`
}

// ReputationSummary defines model for ReputationSummary.
type ReputationSummary struct {
	DnsblHitIps    int     `json:"dnsbl_hit_ips"`
	FlaggedIps     int     `json:"flagged_ips"`
	FlaggedPercent float64 `json:"flagged_percent"`
	TotalIps       int     `json:"total_ips"`
}

// RiskBucket defines model for RiskBucket.
type RiskBucket struct {
	Count int    `json:"count"`
	Label string `json:"label"`
	Max   int    `json:"max"`
	Min   int    `json:"min"`
}

// Rotation defines model for Rotation.
type Rotation struct {
	At                   time.Time `json:"at"`
	FromIp               string    `json:"from_ip"`
	SincePreviousSeconds int64     `json:"since_previous_seconds"`
	ToIp                 string    `json:"to_ip"`
}

// SampleEvent defines model for SampleEvent.
type SampleEvent struct {
	DistinctIps     int       `json:"distinct_ips"`
	EgressCountry   *string   `json:"egress_country,omitempty"`
	Error           string    `json:"error"`
	IpChanged       bool      `json:"ip_changed"`
	NewIps          int       `json:"new_ips"`
	PrimaryCategory string    `json:"primary_category"`
	PrimaryIp       *string   `json:"primary_ip,omitempty"`
	PrimaryRisk     int       `json:"primary_risk"`
	ProbeIps        []*string `json:"probe_ips"`
	ProbeOk         []bool    `json:"probe_ok"`
	ProbeRttsMs     []int     `json:"probe_rtts_ms"`
	ProbesAttempted int       `json:"probes_attempted"`
	ProbesOk        int       `json:"probes_ok"`
	RttMaxMs        int       `json:"rtt_max_ms"`
	RttMedMs        int       `json:"rtt_med_ms"`
	RttMinMs        int       `json:"rtt_min_ms"`
	SampleSeq       int64     `json:"sample_seq"`
	SampledAt       time.Time `json:"sampled_at"`
}

// SamplePage defines model for SamplePage.
type SamplePage struct {
	Items    []SampleEvent `json:"items"`
	Page     int           `json:"page"`
	PageSize int           `json:"page_size"`
	Total    int64         `json:"total"`
}

// SeriesPoint defines model for SeriesPoint.
type SeriesPoint struct {
	At                time.Time `json:"at"`
	Datacenter        int64     `json:"datacenter"`
	DistinctPerSample float64   `json:"distinct_per_sample"`
	IpChanges         int64     `json:"ip_changes"`
	LatencyP50Ms      float64   `json:"latency_p50_ms"`
	LatencyP95Ms      float64   `json:"latency_p95_ms"`
	Mobile            int64     `json:"mobile"`
	Residential       int64     `json:"residential"`
	SuccessRate       float64   `json:"success_rate"`
	Unknown           int64     `json:"unknown"`
}

// Session defines model for Session.
type Session struct {
	CadenceSeconds      int                `json:"cadence_seconds"`
	CreatedAt           time.Time          `json:"created_at"`
	DialTimeoutMs       int                `json:"dial_timeout_ms"`
	DistinctIps         int                `json:"distinct_ips"`
	Id                  openapi_types.UUID `json:"id"`
	LastError           *string            `json:"last_error,omitempty"`
	LastPrimaryCategory *string            `json:"last_primary_category,omitempty"`
	LastPrimaryIp       *string            `json:"last_primary_ip,omitempty"`
	LastRttMs           *int               `json:"last_rtt_ms,omitempty"`
	LastSampleAt        *time.Time         `json:"last_sample_at,omitempty"`
	MaxDurationSeconds  *int               `json:"max_duration_seconds,omitempty"`
	MaxSamples          *int               `json:"max_samples,omitempty"`
	Mode                SessionMode        `json:"mode"`
	Name                string             `json:"name"`
	ProbeTarget         string             `json:"probe_target"`
	ProbesOk            int64              `json:"probes_ok"`
	ProbesPerSample     int                `json:"probes_per_sample"`
	ProbesTotal         int64              `json:"probes_total"`
	ProxyDisplay        string             `json:"proxy_display"`
	SamplesTaken        int                `json:"samples_taken"`
	StartedAt           *time.Time         `json:"started_at,omitempty"`
	Status              SessionStatus      `json:"status"`
	StoppedAt           *time.Time         `json:"stopped_at,omitempty"`
	SuccessRate         float64            `json:"success_rate"`
}

// SessionMode defines model for Session.Mode.
type SessionMode string

// SessionStatus defines model for Session.Status.
type SessionStatus string

// SessionReport defines model for SessionReport.
type SessionReport struct {
	Ips               []IPRow           `json:"ips"`
	PoolComposition   PoolComposition   `json:"pool_composition"`
	PoolGrowth        []PoolGrowthPoint `json:"pool_growth"`
	ReputationSummary ReputationSummary `json:"reputation_summary"`
	RiskHistogram     []RiskBucket      `json:"risk_histogram"`
	Series            []SeriesPoint     `json:"series"`
	Stickiness        Stickiness        `json:"stickiness"`
}

// Stickiness defines model for Stickiness.
type Stickiness struct {
	AverageHoldSeconds float64    `json:"average_hold_seconds"`
	Holds              []Hold     `json:"holds"`
	MedianHoldSeconds  float64    `json:"median_hold_seconds"`
	Rotations          []Rotation `json:"rotations"`
}

// From defines model for From.
type From = time.Time

// SessionID defines model for SessionID.
type SessionID = openapi_types.UUID

// To defines model for To.
type To = time.Time

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Conflict defines model for Conflict.
type Conflict = Error

// DependencyUnavailable defines model for DependencyUnavailable.
type DependencyUnavailable = Error

// InternalError defines model for InternalError.
type InternalError = Error

// NotFound defines model for NotFound.
type NotFound = Error

// ExportSessionCSVParams defines parameters for ExportSessionCSV.
type ExportSessionCSVParams struct {
	From *From `form:"from,omitempty" json:"from,omitempty"`
	To   *To   `form:"to,omitempty" json:"to,omitempty"`
}

// SessionReportParams defines parameters for SessionReport.
type SessionReportParams struct {
	From *From `form:"from,omitempty" json:"from,omitempty"`
	To   *To   `form:"to,omitempty" json:"to,omitempty"`
}

// SessionSamplesParams defines parameters for SessionSamples.
type SessionSamplesParams struct {
	From *From `form:"from,omitempty" json:"from,omitempty"`
	To   *To   `form:"to,omitempty" json:"to,omitempty"`
	Page *int  `form:"page,omitempty" json:"page,omitempty"`
}

// CreateSessionJSONRequestBody defines body for CreateSession for application/json ContentType.
type CreateSessionJSONRequestBody = CreateSessionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/sessions)
	ListSessions(w http.ResponseWriter, r *http.Request)

	// (POST /api/sessions)
	CreateSession(w http.ResponseWriter, r *http.Request)

	// (DELETE /api/sessions/{id})
	DeleteSession(w http.ResponseWriter, r *http.Request, id SessionID)

	// (GET /api/sessions/{id})
	SessionByID(w http.ResponseWriter, r *http.Request, id SessionID)

	// (GET /api/sessions/{id}/export.csv)
	ExportSessionCSV(w http.ResponseWriter, r *http.Request, id SessionID, params ExportSessionCSVParams)

	// (GET /api/sessions/{id}/report)
	SessionReport(w http.ResponseWriter, r *http.Request, id SessionID, params SessionReportParams)

	// (GET /api/sessions/{id}/samples)
	SessionSamples(w http.ResponseWriter, r *http.Request, id SessionID, params SessionSamplesParams)

	// (POST /api/sessions/{id}/stop)
	StopSession(w http.ResponseWriter, r *http.Request, id SessionID)

	// (GET /healthz)
	Healthz(w http.ResponseWriter, r *http.Request)

	// (GET /readyz)
	Readyz(w http.ResponseWriter, r *http.Request)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// (GET /api/sessions)
func (_ Unimplemented) ListSessions(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/sessions)
func (_ Unimplemented) CreateSession(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (DELETE /api/sessions/{id})
func (_ Unimplemented) DeleteSession(w http.ResponseWriter, r *http.Request, id SessionID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/sessions/{id})
func (_ Unimplemented) SessionByID(w http.ResponseWriter, r *http.Request, id SessionID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/sessions/{id}/export.csv)
func (_ Unimplemented) ExportSessionCSV(w http.ResponseWriter, r *http.Request, id SessionID, params ExportSessionCSVParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/sessions/{id}/report)
func (_ Unimplemented) SessionReport(w http.ResponseWriter, r *http.Request, id SessionID, params SessionReportParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /api/sessions/{id}/samples)
func (_ Unimplemented) SessionSamples(w http.ResponseWriter, r *http.Request, id SessionID, params SessionSamplesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (POST /api/sessions/{id}/stop)
func (_ Unimplemented) StopSession(w http.ResponseWriter, r *http.Request, id SessionID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /healthz)
func (_ Unimplemented) Healthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// (GET /readyz)
func (_ Unimplemented) Readyz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListSessions operation middleware
func (siw *ServerInterfaceWrapper) ListSessions(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListSessions(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateSession operation middleware
func (siw *ServerInterfaceWrapper) CreateSession(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateSession(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteSession operation middleware
func (siw *ServerInterfaceWrapper) DeleteSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SessionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SessionByID operation middleware
func (siw *ServerInterfaceWrapper) SessionByID(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SessionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SessionByID(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ExportSessionCSV operation middleware
func (siw *ServerInterfaceWrapper) ExportSessionCSV(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SessionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ExportSessionCSVParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ExportSessionCSV(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SessionReport operation middleware
func (siw *ServerInterfaceWrapper) SessionReport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SessionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SessionReportParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SessionReport(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// SessionSamples operation middleware
func (siw *ServerInterfaceWrapper) SessionSamples(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SessionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params SessionSamplesParams

	// ------------- Optional query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date-time"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "page" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "page", r.URL.Query(), &params.Page, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "page"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "page", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.SessionSamples(w, r, id, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// StopSession operation middleware
func (siw *ServerInterfaceWrapper) StopSession(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id SessionID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.StopSession(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Healthz operation middleware
func (siw *ServerInterfaceWrapper) Healthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Healthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Readyz operation middleware
func (siw *ServerInterfaceWrapper) Readyz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Readyz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sessions", wrapper.ListSessions)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/sessions", wrapper.CreateSession)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api/sessions/{id}", wrapper.DeleteSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sessions/{id}", wrapper.SessionByID)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sessions/{id}/export.csv", wrapper.ExportSessionCSV)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sessions/{id}/report", wrapper.SessionReport)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api/sessions/{id}/samples", wrapper.SessionSamples)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api/sessions/{id}/stop", wrapper.StopSession)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.Healthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/readyz", wrapper.Readyz)
	})

	return r
}

type BadRequestJSONResponse Error

type ConflictJSONResponse Error

type DependencyUnavailableJSONResponse Error

type InternalErrorJSONResponse Error

type NotFoundJSONResponse Error

type ListSessionsRequestObject struct {
}

type ListSessionsResponseObject interface {
	VisitListSessionsResponse(w http.ResponseWriter) error
}

type ListSessions200JSONResponse []Session

func (response ListSessions200JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSessions500JSONResponse struct{ InternalErrorJSONResponse }

func (response ListSessions500JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListSessions503JSONResponse struct {
	DependencyUnavailableJSONResponse
}

func (response ListSessions503JSONResponse) VisitListSessionsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSessionRequestObject struct {
	Body *CreateSessionJSONRequestBody
}

type CreateSessionResponseObject interface {
	VisitCreateSessionResponse(w http.ResponseWriter) error
}

type CreateSession201JSONResponse Session

func (response CreateSession201JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSession400JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response CreateSession500JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSession503JSONResponse struct {
	DependencyUnavailableJSONResponse
}

func (response CreateSession503JSONResponse) VisitCreateSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSessionRequestObject struct {
	Id SessionID `json:"id"`
}

type DeleteSessionResponseObject interface {
	VisitDeleteSessionResponse(w http.ResponseWriter) error
}

type DeleteSession204Response struct {
}

func (response DeleteSession204Response) VisitDeleteSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteSession400JSONResponse struct{ BadRequestJSONResponse }

func (response DeleteSession400JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSession404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteSession404JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSession409JSONResponse struct{ ConflictJSONResponse }

func (response DeleteSession409JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response DeleteSession500JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteSession503JSONResponse struct {
	DependencyUnavailableJSONResponse
}

func (response DeleteSession503JSONResponse) VisitDeleteSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SessionByIDRequestObject struct {
	Id SessionID `json:"id"`
}

type SessionByIDResponseObject interface {
	VisitSessionByIDResponse(w http.ResponseWriter) error
}

type SessionByID200JSONResponse Session

func (response SessionByID200JSONResponse) VisitSessionByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SessionByID400JSONResponse struct{ BadRequestJSONResponse }

func (response SessionByID400JSONResponse) VisitSessionByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SessionByID404JSONResponse struct{ NotFoundJSONResponse }

func (response SessionByID404JSONResponse) VisitSessionByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SessionByID500JSONResponse struct{ InternalErrorJSONResponse }

func (response SessionByID500JSONResponse) VisitSessionByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SessionByID503JSONResponse struct {
	DependencyUnavailableJSONResponse
}

func (response SessionByID503JSONResponse) VisitSessionByIDResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type ExportSessionCSVRequestObject struct {
	Id     SessionID `json:"id"`
	Params ExportSessionCSVParams
}

type ExportSessionCSVResponseObject interface {
	VisitExportSessionCSVResponse(w http.ResponseWriter) error
}

type ExportSessionCSV200ResponseHeaders struct {
	ContentDisposition *string
}

type ExportSessionCSV200TextcsvResponse struct {
	Body          io.Reader
	Headers       ExportSessionCSV200ResponseHeaders
	ContentLength int64
}

func (response ExportSessionCSV200TextcsvResponse) VisitExportSessionCSVResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", "text/csv")
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.ContentDisposition != nil {
		w.Header().Set("Content-Disposition", fmt.Sprint(*response.Headers.ContentDisposition))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type ExportSessionCSV400JSONResponse struct{ BadRequestJSONResponse }

func (response ExportSessionCSV400JSONResponse) VisitExportSessionCSVResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ExportSessionCSV404JSONResponse struct{ NotFoundJSONResponse }

func (response ExportSessionCSV404JSONResponse) VisitExportSessionCSVResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ExportSessionCSV500JSONResponse struct{ InternalErrorJSONResponse }

func (response ExportSessionCSV500JSONResponse) VisitExportSessionCSVResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ExportSessionCSV503JSONResponse struct {
	DependencyUnavailableJSONResponse
}

func (response ExportSessionCSV503JSONResponse) VisitExportSessionCSVResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SessionReportRequestObject struct {
	Id     SessionID `json:"id"`
	Params SessionReportParams
}

type SessionReportResponseObject interface {
	VisitSessionReportResponse(w http.ResponseWriter) error
}

type SessionReport200JSONResponse SessionReport

func (response SessionReport200JSONResponse) VisitSessionReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SessionReport400JSONResponse struct{ BadRequestJSONResponse }

func (response SessionReport400JSONResponse) VisitSessionReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SessionReport404JSONResponse struct{ NotFoundJSONResponse }

func (response SessionReport404JSONResponse) VisitSessionReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SessionReport500JSONResponse struct{ InternalErrorJSONResponse }

func (response SessionReport500JSONResponse) VisitSessionReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SessionReport503JSONResponse struct {
	DependencyUnavailableJSONResponse
}

func (response SessionReport503JSONResponse) VisitSessionReportResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type SessionSamplesRequestObject struct {
	Id     SessionID `json:"id"`
	Params SessionSamplesParams
}

type SessionSamplesResponseObject interface {
	VisitSessionSamplesResponse(w http.ResponseWriter) error
}

type SessionSamples200JSONResponse SamplePage

func (response SessionSamples200JSONResponse) VisitSessionSamplesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SessionSamples400JSONResponse struct{ BadRequestJSONResponse }

func (response SessionSamples400JSONResponse) VisitSessionSamplesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type SessionSamples404JSONResponse struct{ NotFoundJSONResponse }

func (response SessionSamples404JSONResponse) VisitSessionSamplesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type SessionSamples500JSONResponse struct{ InternalErrorJSONResponse }

func (response SessionSamples500JSONResponse) VisitSessionSamplesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type SessionSamples503JSONResponse struct {
	DependencyUnavailableJSONResponse
}

func (response SessionSamples503JSONResponse) VisitSessionSamplesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type StopSessionRequestObject struct {
	Id SessionID `json:"id"`
}

type StopSessionResponseObject interface {
	VisitStopSessionResponse(w http.ResponseWriter) error
}

type StopSession204Response struct {
}

func (response StopSession204Response) VisitStopSessionResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type StopSession400JSONResponse struct{ BadRequestJSONResponse }

func (response StopSession400JSONResponse) VisitStopSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type StopSession404JSONResponse struct{ NotFoundJSONResponse }

func (response StopSession404JSONResponse) VisitStopSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type StopSession409JSONResponse struct{ ConflictJSONResponse }

func (response StopSession409JSONResponse) VisitStopSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(409)
	_, err := buf.WriteTo(w)
	return err
}

type StopSession500JSONResponse struct{ InternalErrorJSONResponse }

func (response StopSession500JSONResponse) VisitStopSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type StopSession503JSONResponse struct {
	DependencyUnavailableJSONResponse
}

func (response StopSession503JSONResponse) VisitStopSessionResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type HealthzRequestObject struct {
}

type HealthzResponseObject interface {
	VisitHealthzResponse(w http.ResponseWriter) error
}

type Healthz200JSONResponse Health

func (response Healthz200JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Healthz500JSONResponse struct{ InternalErrorJSONResponse }

func (response Healthz500JSONResponse) VisitHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ReadyzRequestObject struct {
}

type ReadyzResponseObject interface {
	VisitReadyzResponse(w http.ResponseWriter) error
}

type Readyz200JSONResponse Readiness

func (response Readyz200JSONResponse) VisitReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type Readyz500JSONResponse struct{ InternalErrorJSONResponse }

func (response Readyz500JSONResponse) VisitReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type Readyz503JSONResponse Readiness

func (response Readyz503JSONResponse) VisitReadyzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/sessions)
	ListSessions(ctx context.Context, request ListSessionsRequestObject) (ListSessionsResponseObject, error)

	// (POST /api/sessions)
	CreateSession(ctx context.Context, request CreateSessionRequestObject) (CreateSessionResponseObject, error)

	// (DELETE /api/sessions/{id})
	DeleteSession(ctx context.Context, request DeleteSessionRequestObject) (DeleteSessionResponseObject, error)

	// (GET /api/sessions/{id})
	SessionByID(ctx context.Context, request SessionByIDRequestObject) (SessionByIDResponseObject, error)

	// (GET /api/sessions/{id}/export.csv)
	ExportSessionCSV(ctx context.Context, request ExportSessionCSVRequestObject) (ExportSessionCSVResponseObject, error)

	// (GET /api/sessions/{id}/report)
	SessionReport(ctx context.Context, request SessionReportRequestObject) (SessionReportResponseObject, error)

	// (GET /api/sessions/{id}/samples)
	SessionSamples(ctx context.Context, request SessionSamplesRequestObject) (SessionSamplesResponseObject, error)

	// (POST /api/sessions/{id}/stop)
	StopSession(ctx context.Context, request StopSessionRequestObject) (StopSessionResponseObject, error)

	// (GET /healthz)
	Healthz(ctx context.Context, request HealthzRequestObject) (HealthzResponseObject, error)

	// (GET /readyz)
	Readyz(ctx context.Context, request ReadyzRequestObject) (ReadyzResponseObject, error)
}

type StrictHandlerFunc func(ctx context.Context, w http.ResponseWriter, r *http.Request, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

type StrictHTTPServerOptions struct {
	RequestErrorHandlerFunc  func(w http.ResponseWriter, r *http.Request, err error)
	ResponseErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: StrictHTTPServerOptions{
		RequestErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		},
		ResponseErrorHandlerFunc: func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		},
	}}
}

func NewStrictHandlerWithOptions(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc, options StrictHTTPServerOptions) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares, options: options}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
	options     StrictHTTPServerOptions
}

// ListSessions operation middleware
func (sh *strictHandler) ListSessions(w http.ResponseWriter, r *http.Request) {
	var request ListSessionsRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ListSessions(ctx, request.(ListSessionsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSessions")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ListSessionsResponseObject); ok {
		if err := validResponse.VisitListSessionsResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// CreateSession operation middleware
func (sh *strictHandler) CreateSession(w http.ResponseWriter, r *http.Request) {
	var request CreateSessionRequestObject

	var body CreateSessionJSONRequestBody
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		sh.options.RequestErrorHandlerFunc(w, r, fmt.Errorf("can't decode JSON body: %w", err))
		return
	}
	request.Body = &body

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSession(ctx, request.(CreateSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(CreateSessionResponseObject); ok {
		if err := validResponse.VisitCreateSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// DeleteSession operation middleware
func (sh *strictHandler) DeleteSession(w http.ResponseWriter, r *http.Request, id SessionID) {
	var request DeleteSessionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteSession(ctx, request.(DeleteSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(DeleteSessionResponseObject); ok {
		if err := validResponse.VisitDeleteSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SessionByID operation middleware
func (sh *strictHandler) SessionByID(w http.ResponseWriter, r *http.Request, id SessionID) {
	var request SessionByIDRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SessionByID(ctx, request.(SessionByIDRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SessionByID")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SessionByIDResponseObject); ok {
		if err := validResponse.VisitSessionByIDResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// ExportSessionCSV operation middleware
func (sh *strictHandler) ExportSessionCSV(w http.ResponseWriter, r *http.Request, id SessionID, params ExportSessionCSVParams) {
	var request ExportSessionCSVRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.ExportSessionCSV(ctx, request.(ExportSessionCSVRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ExportSessionCSV")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ExportSessionCSVResponseObject); ok {
		if err := validResponse.VisitExportSessionCSVResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SessionReport operation middleware
func (sh *strictHandler) SessionReport(w http.ResponseWriter, r *http.Request, id SessionID, params SessionReportParams) {
	var request SessionReportRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SessionReport(ctx, request.(SessionReportRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SessionReport")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SessionReportResponseObject); ok {
		if err := validResponse.VisitSessionReportResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// SessionSamples operation middleware
func (sh *strictHandler) SessionSamples(w http.ResponseWriter, r *http.Request, id SessionID, params SessionSamplesParams) {
	var request SessionSamplesRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.SessionSamples(ctx, request.(SessionSamplesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SessionSamples")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(SessionSamplesResponseObject); ok {
		if err := validResponse.VisitSessionSamplesResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// StopSession operation middleware
func (sh *strictHandler) StopSession(w http.ResponseWriter, r *http.Request, id SessionID) {
	var request StopSessionRequestObject

	request.Id = id

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.StopSession(ctx, request.(StopSessionRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StopSession")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(StopSessionResponseObject); ok {
		if err := validResponse.VisitStopSessionResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Healthz operation middleware
func (sh *strictHandler) Healthz(w http.ResponseWriter, r *http.Request) {
	var request HealthzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Healthz(ctx, request.(HealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Healthz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(HealthzResponseObject); ok {
		if err := validResponse.VisitHealthzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Readyz operation middleware
func (sh *strictHandler) Readyz(w http.ResponseWriter, r *http.Request) {
	var request ReadyzRequestObject

	handler := func(ctx context.Context, w http.ResponseWriter, r *http.Request, request interface{}) (interface{}, error) {
		return sh.ssi.Readyz(ctx, request.(ReadyzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "Readyz")
	}

	response, err := handler(r.Context(), w, r, request)

	if err != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, err)
	} else if validResponse, ok := response.(ReadyzResponseObject); ok {
		if err := validResponse.VisitReadyzResponse(w); err != nil {
			sh.options.ResponseErrorHandlerFunc(w, r, err)
		}
	} else if response != nil {
		sh.options.ResponseErrorHandlerFunc(w, r, fmt.Errorf("unexpected response type: %T", response))
	}
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Ftdc9u20v4rHLzvJRMpTXJmqrvESU890+nx2D29yXQ4ELGSUJMAAoC2VY/++xl8iJ9LSrLs5Ca9aUQC",
	"u4vdB4sHy/UjyWWppABhDVk8EkU1LcGC9r9+0bJ0/+eCLMjXCvSWpETQEsiCrNy7lJh8AyV1g1ZSl9SS",
	"BWHUwivLSyApsVvlBhuruViT3S4lN2AMl+LyUy1YUbtp5HJGUqLha8U1MLKwugJUS1X5kUMFf8gxk608",
	"3eCdM8YoKQx4l3yk7Bq+VmCs+5VLYUH4f1KlCp5Ty6WY/W2kcM8aXf+vYUUW5P9mjbtn4a2ZfdZa6qCK",
	"gck1V04IWZBLcUcLzhIdFe5SciHFquD5N1B+DUZWOofEWGohyfeKdyn5BAoEA5Fv/yvoHeUFXRbw8hZ9",
	"SPawSFhtQcJNUrWs2KXkUljQghZB0DeIUlCXGNB3oBMIA1Pyu7S/yEqwbxgrIW2y8jrdoDjPib3QQC3E",
	"vdcCMGWMOyG0uNJSgbbcwXxFCwMpUa1HjySnzuGQGcilYP5RyQUvq5Is3tQbhwsLa/DrZ5wWmdtWsrJZ",
	"6ScwWNGqsGTxZj6fz9OWAPdrKKKkDxmrtHfWmGJRFRGAIVfgUgwtVQFPmSyZxzYIN+ULMZbnty6pKCkL",
	"8tcgY+yzzaNT+xuItd3E5ZVc1L+RaUrLJWSW6jXYbqbTnIyNN5kCHRcXdYa1/fT+fXogPkrLh210yKhh",
	"KbnX3MJ/RLENPgoZcZ+ev4TV7oVFd6UDsDR+ksu/IaSRen+eAsIYjYE3SjCGrrF3PXvzYOB+PGbYr0AL",
	"54zHnnKXCSvTBoO8RRDQUxhnoYpkwYZqMMDXYODC/usdaYUW3TcuObKM2mOPuZRwhbq1tW1ONMFYqu1J",
	"RvT8xhXpSGmtqrErHXoLc/Tl1bW8H3qaGoGuOqcW1lJv8ZeyEnbkHRNmWWQbHsgUtxDS3mBcfEC1pttm",
	"XsGNBdaasJSyACrciBXXxmYGQBwf07WGrZDcQJYX1OCWbLjN/IqeEOIRzHCDPy/oySvQ3NxmJpe6m9ze",
	"dM6O+eE0jkGrDnIT0mB76nHRUT70ZS9mndB3otVed9vdGEyvpCwu3LlveDjZB6mBWpqDIxydgww/O+WS",
	"x0NhcpwGwxkIy2lxeHAlboW8F4cG9vwdTenqSturaSSP+eXfWt7bzZXkAaq9jXxCpmPcWC5ym3F1el7r",
	"Lcznoo5AzPxroIwLCDuwd54VPL/dyMoAvu2VNHatwWBve7bUQ9O2VNweVVmfNG+qsqQhl/WAtkfz3kvT",
	"sFgVdL0GdtpgBTqHXuJhslp6pIzv9ShQVOUyyLPS0uIY1T2HNfO6CxhamPb8gTqVm9uPVX4LCDzrBDvt",
	"mIIuocDZDX2YToDI9ufitCk97wRjgpxgQMyT+OplANR5W3OlZZmNMRHu+KTScMdlZc7gRlbiKrCtvTdo",
	"P2vUDMwnN56jfL4DLGP1sxDC4dxmNtkU3YA9g0boXJZvqFiP0QkB9+OaleYuK2STNGg/KPhy5AAeDneH",
	"6phWd/+JRtXU6aDgPpUKYuQtRsBaDsCnaWtNvKr257YRhM01GbUWStVlcP31mWgZcgxbm7mL6phS/x7Y",
	"9HsuRt8HxpwZ+IrumbEJZxD4lsaONMRhbe/0DtQOlhvgdhbc8U7HlQiYe1hsA68Pgxaa9pttfKNfxetn",
	"d5/XMKr/MVXhaacMDGhRxYF7PV1DZvg/Rwz1R+C5JCisLFrXVr+Xj/oMNAfzHHSuQ4lPPAtqpHWrKAgd",
	"mSIgNUCfchwV1ILIt5l6P49790TttYCf3z9NQHNRONH03s3h1AJBlefugNPUwiEOeGAFrVvJ2Wy+Y9Yg",
	"PAN34xjqYCI9+/4T67YIsRzWZIeOzn3t97RyEFK7ndg9o0yCsyO+2cQbck1mDh75fjhGUk6beSRz8XP8",
	"kTJFSDo72t33w+E34fODiseK3ycXvF+yyP1cZexAi46gJWjZe3TY+AE3Ug/PGDeqoNupamhm6S2IEZp1",
	"uOx5MPDDOrOuhAjVeGOlUp4JrbjgZgMMDU8cdp4Zz5Wg+3yB7T/J9n1efz6IHhh+R8Di38PcMHn1A9dl",
	"mx2kDPJ/j4u2culEor4GJTXCa/qXmykqGErWGAmUssjybpVwSlC/qLgXsfYFtaPt6dfgEMt0XVfKTFNY",
	"mhI6rETti74bbqxca1oebWCrAIPYZjzfPJ6It+gpJs3lx7qkNymoGTm4HwWTOtK6sUGCjXp54LOUjJWp",
	"bjqW92j3HWhH3jeyYGiB5Tg+6aYf72n/DQxxcQmMU3GuLTrWpY63p65kDWzqhS8ss60ixT2Ir2UYHKeA",
	"i5VvX7HcusxMrlx+TMK1UCcfri5JSu5ABzZI3ryev547Q6UCQRUnC/L29fz1W38Lsxu/1hlVfGZCXvIP",
	"4rnsAu/tvmRkQX7jxt7sB/VaXn6az09qYThygwVKO/TyoLuhtmuXkvfBFkxybfOs2wDiZ709PAvvavH2",
	"KGkQn3V6KmLTEhj7UbLts7V8oH0buy4U/Vf5QczePJsNdahGQ5PEYzGhgiWRATm/vzsmWq2Oqu8U4F3a",
	"3SWzR852oV2lgMB9upH/5J+3I99x/bswF3NUkPhU57wLoqen1G1HfsLPhydctFq7vs/+QlNSdNnH7eWn",
	"czPSmehmYCkvvlXMvlOKazV+fsHlNENmTRPn7i9098zgwVHg17m5Gz1zPvshUdTFzZ+Ho2zhwc6iSKSP",
	"c8lFYENIE2c3shcbLYUs5JrntEgU6Ff+FpBc3PyZBMtJSjZAWWyEvQg2vPrETZt2NzYMNP4ACwaW9OBg",
	"33J8xLg/5Cj0dH37msor8Y728pklKsJQ6Hk9sCTan0TLf2Dnu2GnVTWbAs9N3X72cuhpPioh0Pkd7sHY",
	"V77PKFF0DYlcJWstK+XgFK37gaOXx1GK/6lB/BbWhLrpfJ5uyx0FppWq/wcap53TY9eYGyvVU6jsvhL5",
	"g8p2bxIb3z38z2gK+TW+f8HcERuYkbxxpWUOxiTcJLTgd/BUR4WlaqBsO77S6/D6BRfadNYha62jxMEk",
	"VEPizT0bGi9v+AebFECNTaSAqT918f/9LwAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
