// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"net/netip"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type IpReputationCache struct {
	Ip             netip.Addr         `json:"ip"`
	Country        *string            `json:"country"`
	Region         *string            `json:"region"`
	City           *string            `json:"city"`
	Isp            *string            `json:"isp"`
	Asn            *string            `json:"asn"`
	IsMobile       *bool              `json:"is_mobile"`
	IpapiProxy     *bool              `json:"ipapi_proxy"`
	IpapiHosting   *bool              `json:"ipapi_hosting"`
	PcType         *string            `json:"pc_type"`
	PcProxy        *bool              `json:"pc_proxy"`
	RiskScore      *int32             `json:"risk_score"`
	GreynoiseClass *string            `json:"greynoise_class"`
	SfsAppears     *bool              `json:"sfs_appears"`
	SfsFrequency   *int32             `json:"sfs_frequency"`
	DnsblListed    *bool              `json:"dnsbl_listed"`
	DnsblHits      *string            `json:"dnsbl_hits"`
	Category       *string            `json:"category"`
	Raw            []byte             `json:"raw"`
	FirstSeen      pgtype.Timestamptz `json:"first_seen"`
	RefreshedAt    pgtype.Timestamptz `json:"refreshed_at"`
}

type SamplingSession struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	ProxyCiphertext    []byte             `json:"proxy_ciphertext"`
	ProxyNonce         []byte             `json:"proxy_nonce"`
	ProxyDisplay       string             `json:"proxy_display"`
	Mode               string             `json:"mode"`
	CadenceSeconds     int32              `json:"cadence_seconds"`
	ProbesPerSample    int32              `json:"probes_per_sample"`
	ProbeTarget        string             `json:"probe_target"`
	DialTimeoutMs      int32              `json:"dial_timeout_ms"`
	MaxSamples         *int32             `json:"max_samples"`
	MaxDurationSeconds *int32             `json:"max_duration_seconds"`
	Status             string             `json:"status"`
	SamplesTaken       int32              `json:"samples_taken"`
	ProbesOk           int64              `json:"probes_ok"`
	ProbesTotal        int64              `json:"probes_total"`
	DistinctIps        int32              `json:"distinct_ips"`
	LastSampleAt       pgtype.Timestamptz `json:"last_sample_at"`
	LastPrimaryIp      *netip.Addr        `json:"last_primary_ip"`
	LastRttMs          *int32             `json:"last_rtt_ms"`
	LastError          *string            `json:"last_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	StoppedAt          pgtype.Timestamptz `json:"stopped_at"`
	ClaimedBy          *string            `json:"claimed_by"`
	LeaseUntil         pgtype.Timestamptz `json:"lease_until"`
	SequenceOffset     int32              `json:"sequence_offset"`
	RunID              pgtype.UUID        `json:"run_id"`
	VariantParams      []byte             `json:"variant_params"`
	CellKey            *string            `json:"cell_key"`
	TargetCountry      string             `json:"target_country"`
	NameCustomized     bool               `json:"name_customized"`
}

type SessionIp struct {
	SessionID uuid.UUID          `json:"session_id"`
	Ip        netip.Addr         `json:"ip"`
	FirstSeen pgtype.Timestamptz `json:"first_seen"`
	LastSeen  pgtype.Timestamptz `json:"last_seen"`
	HitCount  int64              `json:"hit_count"`
}

type VariationRun struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	TemplateCiphertext []byte             `json:"template_ciphertext"`
	TemplateNonce      []byte             `json:"template_nonce"`
	TemplateDisplay    string             `json:"template_display"`
	Axes               []byte             `json:"axes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}
