// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	DeleteRun(ctx context.Context, id uuid.UUID) error
	DeleteSession(ctx context.Context, id uuid.UUID) error
	FinishSession(ctx context.Context, arg FinishSessionParams) (int64, error)
	InsertRun(ctx context.Context, arg InsertRunParams) error
	InsertRunSession(ctx context.Context, arg InsertRunSessionParams) error
	InsertSession(ctx context.Context, arg InsertSessionParams) error
	// FOR NO KEY UPDATE, not FOR UPDATE: renaming never changes the run's key, and
	// the weaker mode still serializes concurrent run renames against each other
	// while leaving the KEY SHARE lock a child row update takes for its run_id
	// foreign key free. FOR UPDATE would block that, deadlocking this transaction
	// against a concurrent session rename that already holds the child's row lock.
	LockRunForRename(ctx context.Context, id uuid.UUID) (string, error)
	ReenableSession(ctx context.Context, arg ReenableSessionParams) (int64, error)
	// Conditional on the name the cascade read, so a session rename that commits
	// between that read and this write is preserved rather than overwritten.
	RenameGeneratedRunSession(ctx context.Context, arg RenameGeneratedRunSessionParams) (int64, error)
	RenameRun(ctx context.Context, arg RenameRunParams) error
	RenameSession(ctx context.Context, arg RenameSessionParams) (int64, error)
	ReputationByIP(ctx context.Context, ip string) (ReputationByIPRow, error)
	RunByID(ctx context.Context, id uuid.UUID) (RunByIDRow, error)
	RunIPObservations(ctx context.Context, arg RunIPObservationsParams) ([]RunIPObservationsRow, error)
	RunSessionNames(ctx context.Context, runID pgtype.UUID) ([]RunSessionNamesRow, error)
	RunSessions(ctx context.Context, runID pgtype.UUID) ([]RunSessionsRow, error)
	RunningSessions(ctx context.Context) ([]RunningSessionsRow, error)
	Runs(ctx context.Context) ([]RunsRow, error)
	SessionByID(ctx context.Context, id uuid.UUID) (SessionByIDRow, error)
	SessionIPs(ctx context.Context, sessionID uuid.UUID) ([]SessionIPsRow, error)
	Sessions(ctx context.Context) ([]SessionsRow, error)
	SessionsByRun(ctx context.Context, runID pgtype.UUID) ([]uuid.UUID, error)
	StopSession(ctx context.Context, arg StopSessionParams) (int64, error)
	UpdateSessionSnapshot(ctx context.Context, arg UpdateSessionSnapshotParams) error
	UpsertReputation(ctx context.Context, arg UpsertReputationParams) error
	UpsertSessionIP(ctx context.Context, arg UpsertSessionIPParams) error
}

var _ Querier = (*Queries)(nil)
