// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reputation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const reputationByIP = `-- name: ReputationByIP :one
SELECT ip::text AS ip, country, region, city, isp, asn, is_mobile, ipapi_proxy,
  ipapi_hosting, pc_type, pc_proxy, risk_score, greynoise_class, sfs_appears,
  sfs_frequency, dnsbl_listed, dnsbl_hits, category, raw, first_seen, refreshed_at
FROM ip_reputation_cache WHERE ip = $1::text::inet
`

type ReputationByIPRow struct {
	Ip             string             `json:"ip"`
	Country        *string            `json:"country"`
	Region         *string            `json:"region"`
	City           *string            `json:"city"`
	Isp            *string            `json:"isp"`
	Asn            *string            `json:"asn"`
	IsMobile       *bool              `json:"is_mobile"`
	IpapiProxy     *bool              `json:"ipapi_proxy"`
	IpapiHosting   *bool              `json:"ipapi_hosting"`
	PcType         *string            `json:"pc_type"`
	PcProxy        *bool              `json:"pc_proxy"`
	RiskScore      *int32             `json:"risk_score"`
	GreynoiseClass *string            `json:"greynoise_class"`
	SfsAppears     *bool              `json:"sfs_appears"`
	SfsFrequency   *int32             `json:"sfs_frequency"`
	DnsblListed    *bool              `json:"dnsbl_listed"`
	DnsblHits      *string            `json:"dnsbl_hits"`
	Category       *string            `json:"category"`
	Raw            []byte             `json:"raw"`
	FirstSeen      pgtype.Timestamptz `json:"first_seen"`
	RefreshedAt    pgtype.Timestamptz `json:"refreshed_at"`
}

func (q *Queries) ReputationByIP(ctx context.Context, ip string) (ReputationByIPRow, error) {
	row := q.db.QueryRow(ctx, reputationByIP, ip)
	var i ReputationByIPRow
	err := row.Scan(
		&i.Ip,
		&i.Country,
		&i.Region,
		&i.City,
		&i.Isp,
		&i.Asn,
		&i.IsMobile,
		&i.IpapiProxy,
		&i.IpapiHosting,
		&i.PcType,
		&i.PcProxy,
		&i.RiskScore,
		&i.GreynoiseClass,
		&i.SfsAppears,
		&i.SfsFrequency,
		&i.DnsblListed,
		&i.DnsblHits,
		&i.Category,
		&i.Raw,
		&i.FirstSeen,
		&i.RefreshedAt,
	)
	return i, err
}

const upsertReputation = `-- name: UpsertReputation :exec
INSERT INTO ip_reputation_cache (
  ip, country, region, city, isp, asn, is_mobile, ipapi_proxy, ipapi_hosting,
  pc_type, pc_proxy, risk_score, greynoise_class, sfs_appears, sfs_frequency,
  dnsbl_listed, dnsbl_hits, category, raw, first_seen, refreshed_at
) VALUES (
  $1::text::inet, NULLIF($2::text, ''),
  NULLIF($3::text, ''), NULLIF($4::text, ''),
  NULLIF($5::text, ''), NULLIF($6::text, ''),
  $7, $8, $9,
  NULLIF($10::text, ''), $11, $12,
  NULLIF($13::text, ''), $14,
  $15, $16,
  NULLIF($17::text, ''), NULLIF($18::text, ''),
  $19, $20, $21
)
ON CONFLICT (ip) DO UPDATE SET
  country = EXCLUDED.country, region = EXCLUDED.region, city = EXCLUDED.city,
  isp = EXCLUDED.isp, asn = EXCLUDED.asn, is_mobile = EXCLUDED.is_mobile,
  ipapi_proxy = EXCLUDED.ipapi_proxy, ipapi_hosting = EXCLUDED.ipapi_hosting,
  pc_type = EXCLUDED.pc_type, pc_proxy = EXCLUDED.pc_proxy,
  risk_score = EXCLUDED.risk_score, greynoise_class = EXCLUDED.greynoise_class,
  sfs_appears = EXCLUDED.sfs_appears, sfs_frequency = EXCLUDED.sfs_frequency,
  dnsbl_listed = EXCLUDED.dnsbl_listed, dnsbl_hits = EXCLUDED.dnsbl_hits,
  category = EXCLUDED.category, raw = EXCLUDED.raw, refreshed_at = EXCLUDED.refreshed_at
`

type UpsertReputationParams struct {
	Ip             string             `json:"ip"`
	Country        string             `json:"country"`
	Region         string             `json:"region"`
	City           string             `json:"city"`
	Isp            string             `json:"isp"`
	Asn            string             `json:"asn"`
	IsMobile       *bool              `json:"is_mobile"`
	IpapiProxy     *bool              `json:"ipapi_proxy"`
	IpapiHosting   *bool              `json:"ipapi_hosting"`
	PcType         string             `json:"pc_type"`
	PcProxy        *bool              `json:"pc_proxy"`
	RiskScore      *int32             `json:"risk_score"`
	GreynoiseClass string             `json:"greynoise_class"`
	SfsAppears     *bool              `json:"sfs_appears"`
	SfsFrequency   *int32             `json:"sfs_frequency"`
	DnsblListed    *bool              `json:"dnsbl_listed"`
	DnsblHits      string             `json:"dnsbl_hits"`
	Category       string             `json:"category"`
	Raw            []byte             `json:"raw"`
	FirstSeen      pgtype.Timestamptz `json:"first_seen"`
	RefreshedAt    pgtype.Timestamptz `json:"refreshed_at"`
}

func (q *Queries) UpsertReputation(ctx context.Context, arg UpsertReputationParams) error {
	_, err := q.db.Exec(ctx, upsertReputation,
		arg.Ip,
		arg.Country,
		arg.Region,
		arg.City,
		arg.Isp,
		arg.Asn,
		arg.IsMobile,
		arg.IpapiProxy,
		arg.IpapiHosting,
		arg.PcType,
		arg.PcProxy,
		arg.RiskScore,
		arg.GreynoiseClass,
		arg.SfsAppears,
		arg.SfsFrequency,
		arg.DnsblListed,
		arg.DnsblHits,
		arg.Category,
		arg.Raw,
		arg.FirstSeen,
		arg.RefreshedAt,
	)
	return err
}
