// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runs.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteRun = `-- name: DeleteRun :exec
DELETE FROM variation_runs WHERE id = $1
`

func (q *Queries) DeleteRun(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteRun, id)
	return err
}

const insertRun = `-- name: InsertRun :exec
INSERT INTO variation_runs (id, name, template_ciphertext, template_nonce, template_display, axes, created_at)
VALUES ($1, $2, $3, $4,
  $5, $6, $7)
`

type InsertRunParams struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	TemplateCiphertext []byte             `json:"template_ciphertext"`
	TemplateNonce      []byte             `json:"template_nonce"`
	TemplateDisplay    string             `json:"template_display"`
	Axes               []byte             `json:"axes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) InsertRun(ctx context.Context, arg InsertRunParams) error {
	_, err := q.db.Exec(ctx, insertRun,
		arg.ID,
		arg.Name,
		arg.TemplateCiphertext,
		arg.TemplateNonce,
		arg.TemplateDisplay,
		arg.Axes,
		arg.CreatedAt,
	)
	return err
}

const insertRunSession = `-- name: InsertRunSession :exec
INSERT INTO sampling_sessions (
  id, name, proxy_ciphertext, proxy_nonce, proxy_display, mode,
  cadence_seconds, probes_per_sample, probe_target, dial_timeout_ms,
  max_samples, max_duration_seconds, status, samples_taken, probes_ok,
  probes_total, distinct_ips, last_sample_at, last_primary_ip, last_rtt_ms,
  last_error, created_at, started_at, stopped_at, sequence_offset,
  target_country, run_id, variant_params, cell_key
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10,
  $11, $12, $13,
  $14, $15, $16,
  $17, $18,
  NULLIF($19::text, '')::inet, $20,
  NULLIF($21::text, ''), $22,
  $23, $24, $25,
  $26, $27, $28, $29
)
`

type InsertRunSessionParams struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	ProxyCiphertext    []byte             `json:"proxy_ciphertext"`
	ProxyNonce         []byte             `json:"proxy_nonce"`
	ProxyDisplay       string             `json:"proxy_display"`
	Mode               string             `json:"mode"`
	CadenceSeconds     int32              `json:"cadence_seconds"`
	ProbesPerSample    int32              `json:"probes_per_sample"`
	ProbeTarget        string             `json:"probe_target"`
	DialTimeoutMs      int32              `json:"dial_timeout_ms"`
	MaxSamples         *int32             `json:"max_samples"`
	MaxDurationSeconds *int32             `json:"max_duration_seconds"`
	Status             string             `json:"status"`
	SamplesTaken       int32              `json:"samples_taken"`
	ProbesOk           int64              `json:"probes_ok"`
	ProbesTotal        int64              `json:"probes_total"`
	DistinctIps        int32              `json:"distinct_ips"`
	LastSampleAt       pgtype.Timestamptz `json:"last_sample_at"`
	LastPrimaryIp      string             `json:"last_primary_ip"`
	LastRttMs          *int32             `json:"last_rtt_ms"`
	LastError          string             `json:"last_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	StoppedAt          pgtype.Timestamptz `json:"stopped_at"`
	SequenceOffset     int32              `json:"sequence_offset"`
	TargetCountry      string             `json:"target_country"`
	RunID              pgtype.UUID        `json:"run_id"`
	VariantParams      []byte             `json:"variant_params"`
	CellKey            *string            `json:"cell_key"`
}

func (q *Queries) InsertRunSession(ctx context.Context, arg InsertRunSessionParams) error {
	_, err := q.db.Exec(ctx, insertRunSession,
		arg.ID,
		arg.Name,
		arg.ProxyCiphertext,
		arg.ProxyNonce,
		arg.ProxyDisplay,
		arg.Mode,
		arg.CadenceSeconds,
		arg.ProbesPerSample,
		arg.ProbeTarget,
		arg.DialTimeoutMs,
		arg.MaxSamples,
		arg.MaxDurationSeconds,
		arg.Status,
		arg.SamplesTaken,
		arg.ProbesOk,
		arg.ProbesTotal,
		arg.DistinctIps,
		arg.LastSampleAt,
		arg.LastPrimaryIp,
		arg.LastRttMs,
		arg.LastError,
		arg.CreatedAt,
		arg.StartedAt,
		arg.StoppedAt,
		arg.SequenceOffset,
		arg.TargetCountry,
		arg.RunID,
		arg.VariantParams,
		arg.CellKey,
	)
	return err
}

const lockRunForRename = `-- name: LockRunForRename :one
SELECT run.name
FROM variation_runs AS run
WHERE run.id = $1
FOR NO KEY UPDATE
`

// FOR NO KEY UPDATE, not FOR UPDATE: renaming never changes the run's key, and
// the weaker mode still serializes concurrent run renames against each other
// while leaving the KEY SHARE lock a child row update takes for its run_id
// foreign key free. FOR UPDATE would block that, deadlocking this transaction
// against a concurrent session rename that already holds the child's row lock.
func (q *Queries) LockRunForRename(ctx context.Context, id uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, lockRunForRename, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const renameGeneratedRunSession = `-- name: RenameGeneratedRunSession :execrows
UPDATE sampling_sessions
SET name = $1
WHERE id = $2 AND name = $3
`

type RenameGeneratedRunSessionParams struct {
	Name         string    `json:"name"`
	ID           uuid.UUID `json:"id"`
	ExpectedName string    `json:"expected_name"`
}

// Conditional on the name the cascade read, so a session rename that commits
// between that read and this write is preserved rather than overwritten.
func (q *Queries) RenameGeneratedRunSession(ctx context.Context, arg RenameGeneratedRunSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameGeneratedRunSession, arg.Name, arg.ID, arg.ExpectedName)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameRun = `-- name: RenameRun :exec
UPDATE variation_runs
SET name = $1
WHERE id = $2
`

type RenameRunParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) RenameRun(ctx context.Context, arg RenameRunParams) error {
	_, err := q.db.Exec(ctx, renameRun, arg.Name, arg.ID)
	return err
}

const runByID = `-- name: RunByID :one
SELECT
  run.id, run.name, run.template_ciphertext, run.template_nonce, run.template_display,
  run.axes, run.created_at,
  COUNT(s.id) AS variant_count,
  (SELECT COUNT(DISTINCT si.ip) FROM session_ips AS si
     JOIN sampling_sessions AS c ON c.id = si.session_id
     WHERE c.run_id = run.id)::bigint AS distinct_ips,
  COUNT(*) FILTER (WHERE s.status = 'running') AS running_count,
  COUNT(*) FILTER (WHERE s.status = 'finished') AS finished_count
FROM variation_runs AS run
LEFT JOIN sampling_sessions AS s ON s.run_id = run.id
WHERE run.id = $1
GROUP BY run.id
`

type RunByIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	TemplateCiphertext []byte             `json:"template_ciphertext"`
	TemplateNonce      []byte             `json:"template_nonce"`
	TemplateDisplay    string             `json:"template_display"`
	Axes               []byte             `json:"axes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	VariantCount       int64              `json:"variant_count"`
	DistinctIps        int64              `json:"distinct_ips"`
	RunningCount       int64              `json:"running_count"`
	FinishedCount      int64              `json:"finished_count"`
}

func (q *Queries) RunByID(ctx context.Context, id uuid.UUID) (RunByIDRow, error) {
	row := q.db.QueryRow(ctx, runByID, id)
	var i RunByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.TemplateCiphertext,
		&i.TemplateNonce,
		&i.TemplateDisplay,
		&i.Axes,
		&i.CreatedAt,
		&i.VariantCount,
		&i.DistinctIps,
		&i.RunningCount,
		&i.FinishedCount,
	)
	return i, err
}

const runIPObservations = `-- name: RunIPObservations :many
SELECT
  si.session_id, si.ip::text AS ip, si.hit_count, si.first_seen, si.last_seen,
  CAST(COALESCE(r.ip::text, '') AS text) AS reputation_ip, r.country, r.region, r.city, r.isp, r.asn,
  r.is_mobile, r.ipapi_proxy, r.ipapi_hosting, r.pc_type, r.pc_proxy,
  r.risk_score, r.greynoise_class, r.sfs_appears, r.sfs_frequency,
  r.dnsbl_listed, r.dnsbl_hits, r.category, r.raw, r.first_seen AS reputation_first_seen,
  r.refreshed_at
FROM session_ips AS si
JOIN sampling_sessions AS s ON s.id = si.session_id
LEFT JOIN ip_reputation_cache AS r ON r.ip = si.ip
WHERE s.run_id = $1
ORDER BY si.last_seen DESC
LIMIT $2
`

type RunIPObservationsParams struct {
	RunID    pgtype.UUID `json:"run_id"`
	RowLimit int32       `json:"row_limit"`
}

type RunIPObservationsRow struct {
	SessionID           uuid.UUID          `json:"session_id"`
	Ip                  string             `json:"ip"`
	HitCount            int64              `json:"hit_count"`
	FirstSeen           pgtype.Timestamptz `json:"first_seen"`
	LastSeen            pgtype.Timestamptz `json:"last_seen"`
	ReputationIp        string             `json:"reputation_ip"`
	Country             *string            `json:"country"`
	Region              *string            `json:"region"`
	City                *string            `json:"city"`
	Isp                 *string            `json:"isp"`
	Asn                 *string            `json:"asn"`
	IsMobile            *bool              `json:"is_mobile"`
	IpapiProxy          *bool              `json:"ipapi_proxy"`
	IpapiHosting        *bool              `json:"ipapi_hosting"`
	PcType              *string            `json:"pc_type"`
	PcProxy             *bool              `json:"pc_proxy"`
	RiskScore           *int32             `json:"risk_score"`
	GreynoiseClass      *string            `json:"greynoise_class"`
	SfsAppears          *bool              `json:"sfs_appears"`
	SfsFrequency        *int32             `json:"sfs_frequency"`
	DnsblListed         *bool              `json:"dnsbl_listed"`
	DnsblHits           *string            `json:"dnsbl_hits"`
	Category            *string            `json:"category"`
	Raw                 []byte             `json:"raw"`
	ReputationFirstSeen pgtype.Timestamptz `json:"reputation_first_seen"`
	RefreshedAt         pgtype.Timestamptz `json:"refreshed_at"`
}

func (q *Queries) RunIPObservations(ctx context.Context, arg RunIPObservationsParams) ([]RunIPObservationsRow, error) {
	rows, err := q.db.Query(ctx, runIPObservations, arg.RunID, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunIPObservationsRow
	for rows.Next() {
		var i RunIPObservationsRow
		if err := rows.Scan(
			&i.SessionID,
			&i.Ip,
			&i.HitCount,
			&i.FirstSeen,
			&i.LastSeen,
			&i.ReputationIp,
			&i.Country,
			&i.Region,
			&i.City,
			&i.Isp,
			&i.Asn,
			&i.IsMobile,
			&i.IpapiProxy,
			&i.IpapiHosting,
			&i.PcType,
			&i.PcProxy,
			&i.RiskScore,
			&i.GreynoiseClass,
			&i.SfsAppears,
			&i.SfsFrequency,
			&i.DnsblListed,
			&i.DnsblHits,
			&i.Category,
			&i.Raw,
			&i.ReputationFirstSeen,
			&i.RefreshedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runSessionNames = `-- name: RunSessionNames :many
SELECT s.id, s.name, COALESCE(s.variant_params, '{}'::jsonb) AS variant_params
FROM sampling_sessions AS s
WHERE s.run_id = $1
ORDER BY s.created_at ASC, s.id ASC
`

type RunSessionNamesRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	VariantParams []byte    `json:"variant_params"`
}

func (q *Queries) RunSessionNames(ctx context.Context, runID pgtype.UUID) ([]RunSessionNamesRow, error) {
	rows, err := q.db.Query(ctx, runSessionNames, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunSessionNamesRow
	for rows.Next() {
		var i RunSessionNamesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.VariantParams); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runSessions = `-- name: RunSessions :many
SELECT
  s.id, s.name, COALESCE(s.variant_params, '{}'::jsonb) AS variant_params,
  COALESCE(s.cell_key, '') AS cell_key, s.target_country, s.status,
  s.samples_taken, s.probes_ok, s.probes_total, s.distinct_ips
FROM sampling_sessions AS s
WHERE s.run_id = $1
ORDER BY s.created_at ASC, s.id ASC
`

type RunSessionsRow struct {
	ID            uuid.UUID `json:"id"`
	Name          string    `json:"name"`
	VariantParams []byte    `json:"variant_params"`
	CellKey       string    `json:"cell_key"`
	TargetCountry string    `json:"target_country"`
	Status        string    `json:"status"`
	SamplesTaken  int32     `json:"samples_taken"`
	ProbesOk      int64     `json:"probes_ok"`
	ProbesTotal   int64     `json:"probes_total"`
	DistinctIps   int32     `json:"distinct_ips"`
}

func (q *Queries) RunSessions(ctx context.Context, runID pgtype.UUID) ([]RunSessionsRow, error) {
	rows, err := q.db.Query(ctx, runSessions, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunSessionsRow
	for rows.Next() {
		var i RunSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.VariantParams,
			&i.CellKey,
			&i.TargetCountry,
			&i.Status,
			&i.SamplesTaken,
			&i.ProbesOk,
			&i.ProbesTotal,
			&i.DistinctIps,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const runs = `-- name: Runs :many
SELECT
  run.id, run.name, run.template_ciphertext, run.template_nonce, run.template_display,
  run.axes, run.created_at,
  COUNT(s.id) AS variant_count,
  (SELECT COUNT(DISTINCT si.ip) FROM session_ips AS si
     JOIN sampling_sessions AS c ON c.id = si.session_id
     WHERE c.run_id = run.id)::bigint AS distinct_ips,
  COUNT(*) FILTER (WHERE s.status = 'running') AS running_count,
  COUNT(*) FILTER (WHERE s.status = 'finished') AS finished_count
FROM variation_runs AS run
LEFT JOIN sampling_sessions AS s ON s.run_id = run.id
GROUP BY run.id
ORDER BY run.created_at DESC
`

type RunsRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	TemplateCiphertext []byte             `json:"template_ciphertext"`
	TemplateNonce      []byte             `json:"template_nonce"`
	TemplateDisplay    string             `json:"template_display"`
	Axes               []byte             `json:"axes"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	VariantCount       int64              `json:"variant_count"`
	DistinctIps        int64              `json:"distinct_ips"`
	RunningCount       int64              `json:"running_count"`
	FinishedCount      int64              `json:"finished_count"`
}

func (q *Queries) Runs(ctx context.Context) ([]RunsRow, error) {
	rows, err := q.db.Query(ctx, runs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunsRow
	for rows.Next() {
		var i RunsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.TemplateCiphertext,
			&i.TemplateNonce,
			&i.TemplateDisplay,
			&i.Axes,
			&i.CreatedAt,
			&i.VariantCount,
			&i.DistinctIps,
			&i.RunningCount,
			&i.FinishedCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionsByRun = `-- name: SessionsByRun :many
SELECT s.id
FROM sampling_sessions AS s
WHERE s.run_id = $1
ORDER BY s.created_at ASC, s.id ASC
`

func (q *Queries) SessionsByRun(ctx context.Context, runID pgtype.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, sessionsByRun, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
