// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sessions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const deleteSession = `-- name: DeleteSession :exec
DELETE FROM sampling_sessions WHERE id = $1
`

func (q *Queries) DeleteSession(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteSession, id)
	return err
}

const finishSession = `-- name: FinishSession :execrows
UPDATE sampling_sessions
SET status = 'finished', stopped_at = $1
WHERE id = $2 AND status = 'running'
`

type FinishSessionParams struct {
	StoppedAt pgtype.Timestamptz `json:"stopped_at"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) FinishSession(ctx context.Context, arg FinishSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, finishSession, arg.StoppedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertSession = `-- name: InsertSession :exec
INSERT INTO sampling_sessions (
  id, name, proxy_ciphertext, proxy_nonce, proxy_display, mode,
  cadence_seconds, probes_per_sample, probe_target, dial_timeout_ms,
  max_samples, max_duration_seconds, status, samples_taken, probes_ok,
  probes_total, distinct_ips, last_sample_at, last_primary_ip, last_rtt_ms,
  last_error, created_at, started_at, stopped_at, sequence_offset,
  target_country
) VALUES (
  $1, $2, $3, $4,
  $5, $6, $7,
  $8, $9, $10,
  $11, $12, $13,
  $14, $15, $16,
  $17, $18,
  NULLIF($19::text, '')::inet, $20,
  NULLIF($21::text, ''), $22,
  $23, $24, $25,
  $26
)
`

type InsertSessionParams struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	ProxyCiphertext    []byte             `json:"proxy_ciphertext"`
	ProxyNonce         []byte             `json:"proxy_nonce"`
	ProxyDisplay       string             `json:"proxy_display"`
	Mode               string             `json:"mode"`
	CadenceSeconds     int32              `json:"cadence_seconds"`
	ProbesPerSample    int32              `json:"probes_per_sample"`
	ProbeTarget        string             `json:"probe_target"`
	DialTimeoutMs      int32              `json:"dial_timeout_ms"`
	MaxSamples         *int32             `json:"max_samples"`
	MaxDurationSeconds *int32             `json:"max_duration_seconds"`
	Status             string             `json:"status"`
	SamplesTaken       int32              `json:"samples_taken"`
	ProbesOk           int64              `json:"probes_ok"`
	ProbesTotal        int64              `json:"probes_total"`
	DistinctIps        int32              `json:"distinct_ips"`
	LastSampleAt       pgtype.Timestamptz `json:"last_sample_at"`
	LastPrimaryIp      string             `json:"last_primary_ip"`
	LastRttMs          *int32             `json:"last_rtt_ms"`
	LastError          string             `json:"last_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	StoppedAt          pgtype.Timestamptz `json:"stopped_at"`
	SequenceOffset     int32              `json:"sequence_offset"`
	TargetCountry      string             `json:"target_country"`
}

func (q *Queries) InsertSession(ctx context.Context, arg InsertSessionParams) error {
	_, err := q.db.Exec(ctx, insertSession,
		arg.ID,
		arg.Name,
		arg.ProxyCiphertext,
		arg.ProxyNonce,
		arg.ProxyDisplay,
		arg.Mode,
		arg.CadenceSeconds,
		arg.ProbesPerSample,
		arg.ProbeTarget,
		arg.DialTimeoutMs,
		arg.MaxSamples,
		arg.MaxDurationSeconds,
		arg.Status,
		arg.SamplesTaken,
		arg.ProbesOk,
		arg.ProbesTotal,
		arg.DistinctIps,
		arg.LastSampleAt,
		arg.LastPrimaryIp,
		arg.LastRttMs,
		arg.LastError,
		arg.CreatedAt,
		arg.StartedAt,
		arg.StoppedAt,
		arg.SequenceOffset,
		arg.TargetCountry,
	)
	return err
}

const reenableSession = `-- name: ReenableSession :execrows
UPDATE sampling_sessions
SET status = 'running',
    sequence_offset = sequence_offset + samples_taken,
    samples_taken = 0,
    probes_ok = 0,
    probes_total = 0,
    last_sample_at = NULL,
    last_primary_ip = NULL,
    last_rtt_ms = NULL,
    last_error = NULL,
    started_at = $1,
    stopped_at = NULL
WHERE id = $2 AND status IN ('stopped', 'finished')
`

type ReenableSessionParams struct {
	StartedAt pgtype.Timestamptz `json:"started_at"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) ReenableSession(ctx context.Context, arg ReenableSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, reenableSession, arg.StartedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const renameSession = `-- name: RenameSession :execrows
UPDATE sampling_sessions
SET name = $1
WHERE id = $2
`

type RenameSessionParams struct {
	Name string    `json:"name"`
	ID   uuid.UUID `json:"id"`
}

func (q *Queries) RenameSession(ctx context.Context, arg RenameSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, renameSession, arg.Name, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const runningSessions = `-- name: RunningSessions :many
SELECT
  s.id, s.name, s.proxy_ciphertext, s.proxy_nonce, s.proxy_display, s.mode,
  s.cadence_seconds, s.probes_per_sample, s.probe_target, s.dial_timeout_ms,
  s.max_samples, s.max_duration_seconds, s.status, s.samples_taken, s.probes_ok,
  s.probes_total, s.distinct_ips, s.last_sample_at, CAST(COALESCE(s.last_primary_ip::text, '') AS text) AS last_primary_ip,
  COALESCE(r.category, '') AS last_category, s.last_rtt_ms, s.last_error,
  s.created_at, s.started_at, s.stopped_at, s.sequence_offset, s.target_country
FROM sampling_sessions AS s
LEFT JOIN ip_reputation_cache AS r ON r.ip = s.last_primary_ip
WHERE s.status = 'running'
ORDER BY s.created_at ASC
`

type RunningSessionsRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	ProxyCiphertext    []byte             `json:"proxy_ciphertext"`
	ProxyNonce         []byte             `json:"proxy_nonce"`
	ProxyDisplay       string             `json:"proxy_display"`
	Mode               string             `json:"mode"`
	CadenceSeconds     int32              `json:"cadence_seconds"`
	ProbesPerSample    int32              `json:"probes_per_sample"`
	ProbeTarget        string             `json:"probe_target"`
	DialTimeoutMs      int32              `json:"dial_timeout_ms"`
	MaxSamples         *int32             `json:"max_samples"`
	MaxDurationSeconds *int32             `json:"max_duration_seconds"`
	Status             string             `json:"status"`
	SamplesTaken       int32              `json:"samples_taken"`
	ProbesOk           int64              `json:"probes_ok"`
	ProbesTotal        int64              `json:"probes_total"`
	DistinctIps        int32              `json:"distinct_ips"`
	LastSampleAt       pgtype.Timestamptz `json:"last_sample_at"`
	LastPrimaryIp      string             `json:"last_primary_ip"`
	LastCategory       string             `json:"last_category"`
	LastRttMs          *int32             `json:"last_rtt_ms"`
	LastError          *string            `json:"last_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	StoppedAt          pgtype.Timestamptz `json:"stopped_at"`
	SequenceOffset     int32              `json:"sequence_offset"`
	TargetCountry      string             `json:"target_country"`
}

func (q *Queries) RunningSessions(ctx context.Context) ([]RunningSessionsRow, error) {
	rows, err := q.db.Query(ctx, runningSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RunningSessionsRow
	for rows.Next() {
		var i RunningSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProxyCiphertext,
			&i.ProxyNonce,
			&i.ProxyDisplay,
			&i.Mode,
			&i.CadenceSeconds,
			&i.ProbesPerSample,
			&i.ProbeTarget,
			&i.DialTimeoutMs,
			&i.MaxSamples,
			&i.MaxDurationSeconds,
			&i.Status,
			&i.SamplesTaken,
			&i.ProbesOk,
			&i.ProbesTotal,
			&i.DistinctIps,
			&i.LastSampleAt,
			&i.LastPrimaryIp,
			&i.LastCategory,
			&i.LastRttMs,
			&i.LastError,
			&i.CreatedAt,
			&i.StartedAt,
			&i.StoppedAt,
			&i.SequenceOffset,
			&i.TargetCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessionByID = `-- name: SessionByID :one
SELECT
  s.id, s.name, s.proxy_ciphertext, s.proxy_nonce, s.proxy_display, s.mode,
  s.cadence_seconds, s.probes_per_sample, s.probe_target, s.dial_timeout_ms,
  s.max_samples, s.max_duration_seconds, s.status, s.samples_taken, s.probes_ok,
  s.probes_total, s.distinct_ips, s.last_sample_at, CAST(COALESCE(s.last_primary_ip::text, '') AS text) AS last_primary_ip,
  COALESCE(r.category, '') AS last_category, s.last_rtt_ms, s.last_error,
  s.created_at, s.started_at, s.stopped_at, s.sequence_offset, s.target_country
FROM sampling_sessions AS s
LEFT JOIN ip_reputation_cache AS r ON r.ip = s.last_primary_ip
WHERE s.id = $1
`

type SessionByIDRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	ProxyCiphertext    []byte             `json:"proxy_ciphertext"`
	ProxyNonce         []byte             `json:"proxy_nonce"`
	ProxyDisplay       string             `json:"proxy_display"`
	Mode               string             `json:"mode"`
	CadenceSeconds     int32              `json:"cadence_seconds"`
	ProbesPerSample    int32              `json:"probes_per_sample"`
	ProbeTarget        string             `json:"probe_target"`
	DialTimeoutMs      int32              `json:"dial_timeout_ms"`
	MaxSamples         *int32             `json:"max_samples"`
	MaxDurationSeconds *int32             `json:"max_duration_seconds"`
	Status             string             `json:"status"`
	SamplesTaken       int32              `json:"samples_taken"`
	ProbesOk           int64              `json:"probes_ok"`
	ProbesTotal        int64              `json:"probes_total"`
	DistinctIps        int32              `json:"distinct_ips"`
	LastSampleAt       pgtype.Timestamptz `json:"last_sample_at"`
	LastPrimaryIp      string             `json:"last_primary_ip"`
	LastCategory       string             `json:"last_category"`
	LastRttMs          *int32             `json:"last_rtt_ms"`
	LastError          *string            `json:"last_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	StoppedAt          pgtype.Timestamptz `json:"stopped_at"`
	SequenceOffset     int32              `json:"sequence_offset"`
	TargetCountry      string             `json:"target_country"`
}

func (q *Queries) SessionByID(ctx context.Context, id uuid.UUID) (SessionByIDRow, error) {
	row := q.db.QueryRow(ctx, sessionByID, id)
	var i SessionByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ProxyCiphertext,
		&i.ProxyNonce,
		&i.ProxyDisplay,
		&i.Mode,
		&i.CadenceSeconds,
		&i.ProbesPerSample,
		&i.ProbeTarget,
		&i.DialTimeoutMs,
		&i.MaxSamples,
		&i.MaxDurationSeconds,
		&i.Status,
		&i.SamplesTaken,
		&i.ProbesOk,
		&i.ProbesTotal,
		&i.DistinctIps,
		&i.LastSampleAt,
		&i.LastPrimaryIp,
		&i.LastCategory,
		&i.LastRttMs,
		&i.LastError,
		&i.CreatedAt,
		&i.StartedAt,
		&i.StoppedAt,
		&i.SequenceOffset,
		&i.TargetCountry,
	)
	return i, err
}

const sessionIPs = `-- name: SessionIPs :many
SELECT
  si.ip::text AS ip, si.first_seen, si.last_seen, si.hit_count,
  CAST(COALESCE(r.ip::text, '') AS text) AS reputation_ip, r.country, r.region, r.city, r.isp, r.asn,
  r.is_mobile, r.ipapi_proxy, r.ipapi_hosting, r.pc_type, r.pc_proxy,
  r.risk_score, r.greynoise_class, r.sfs_appears, r.sfs_frequency,
  r.dnsbl_listed, r.dnsbl_hits, r.category, r.raw, r.first_seen AS reputation_first_seen,
  r.refreshed_at
FROM session_ips AS si
LEFT JOIN ip_reputation_cache AS r ON r.ip = si.ip
WHERE si.session_id = $1
ORDER BY si.last_seen DESC
`

type SessionIPsRow struct {
	Ip                  string             `json:"ip"`
	FirstSeen           pgtype.Timestamptz `json:"first_seen"`
	LastSeen            pgtype.Timestamptz `json:"last_seen"`
	HitCount            int64              `json:"hit_count"`
	ReputationIp        string             `json:"reputation_ip"`
	Country             *string            `json:"country"`
	Region              *string            `json:"region"`
	City                *string            `json:"city"`
	Isp                 *string            `json:"isp"`
	Asn                 *string            `json:"asn"`
	IsMobile            *bool              `json:"is_mobile"`
	IpapiProxy          *bool              `json:"ipapi_proxy"`
	IpapiHosting        *bool              `json:"ipapi_hosting"`
	PcType              *string            `json:"pc_type"`
	PcProxy             *bool              `json:"pc_proxy"`
	RiskScore           *int32             `json:"risk_score"`
	GreynoiseClass      *string            `json:"greynoise_class"`
	SfsAppears          *bool              `json:"sfs_appears"`
	SfsFrequency        *int32             `json:"sfs_frequency"`
	DnsblListed         *bool              `json:"dnsbl_listed"`
	DnsblHits           *string            `json:"dnsbl_hits"`
	Category            *string            `json:"category"`
	Raw                 []byte             `json:"raw"`
	ReputationFirstSeen pgtype.Timestamptz `json:"reputation_first_seen"`
	RefreshedAt         pgtype.Timestamptz `json:"refreshed_at"`
}

func (q *Queries) SessionIPs(ctx context.Context, sessionID uuid.UUID) ([]SessionIPsRow, error) {
	rows, err := q.db.Query(ctx, sessionIPs, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionIPsRow
	for rows.Next() {
		var i SessionIPsRow
		if err := rows.Scan(
			&i.Ip,
			&i.FirstSeen,
			&i.LastSeen,
			&i.HitCount,
			&i.ReputationIp,
			&i.Country,
			&i.Region,
			&i.City,
			&i.Isp,
			&i.Asn,
			&i.IsMobile,
			&i.IpapiProxy,
			&i.IpapiHosting,
			&i.PcType,
			&i.PcProxy,
			&i.RiskScore,
			&i.GreynoiseClass,
			&i.SfsAppears,
			&i.SfsFrequency,
			&i.DnsblListed,
			&i.DnsblHits,
			&i.Category,
			&i.Raw,
			&i.ReputationFirstSeen,
			&i.RefreshedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sessions = `-- name: Sessions :many
SELECT
  s.id, s.name, s.proxy_ciphertext, s.proxy_nonce, s.proxy_display, s.mode,
  s.cadence_seconds, s.probes_per_sample, s.probe_target, s.dial_timeout_ms,
  s.max_samples, s.max_duration_seconds, s.status, s.samples_taken, s.probes_ok,
  s.probes_total, s.distinct_ips, s.last_sample_at, CAST(COALESCE(s.last_primary_ip::text, '') AS text) AS last_primary_ip,
  COALESCE(r.category, '') AS last_category, s.last_rtt_ms, s.last_error,
  s.created_at, s.started_at, s.stopped_at, s.sequence_offset, s.target_country
FROM sampling_sessions AS s
LEFT JOIN ip_reputation_cache AS r ON r.ip = s.last_primary_ip
WHERE s.run_id IS NULL
ORDER BY s.created_at DESC
`

type SessionsRow struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	ProxyCiphertext    []byte             `json:"proxy_ciphertext"`
	ProxyNonce         []byte             `json:"proxy_nonce"`
	ProxyDisplay       string             `json:"proxy_display"`
	Mode               string             `json:"mode"`
	CadenceSeconds     int32              `json:"cadence_seconds"`
	ProbesPerSample    int32              `json:"probes_per_sample"`
	ProbeTarget        string             `json:"probe_target"`
	DialTimeoutMs      int32              `json:"dial_timeout_ms"`
	MaxSamples         *int32             `json:"max_samples"`
	MaxDurationSeconds *int32             `json:"max_duration_seconds"`
	Status             string             `json:"status"`
	SamplesTaken       int32              `json:"samples_taken"`
	ProbesOk           int64              `json:"probes_ok"`
	ProbesTotal        int64              `json:"probes_total"`
	DistinctIps        int32              `json:"distinct_ips"`
	LastSampleAt       pgtype.Timestamptz `json:"last_sample_at"`
	LastPrimaryIp      string             `json:"last_primary_ip"`
	LastCategory       string             `json:"last_category"`
	LastRttMs          *int32             `json:"last_rtt_ms"`
	LastError          *string            `json:"last_error"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	StartedAt          pgtype.Timestamptz `json:"started_at"`
	StoppedAt          pgtype.Timestamptz `json:"stopped_at"`
	SequenceOffset     int32              `json:"sequence_offset"`
	TargetCountry      string             `json:"target_country"`
}

func (q *Queries) Sessions(ctx context.Context) ([]SessionsRow, error) {
	rows, err := q.db.Query(ctx, sessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SessionsRow
	for rows.Next() {
		var i SessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ProxyCiphertext,
			&i.ProxyNonce,
			&i.ProxyDisplay,
			&i.Mode,
			&i.CadenceSeconds,
			&i.ProbesPerSample,
			&i.ProbeTarget,
			&i.DialTimeoutMs,
			&i.MaxSamples,
			&i.MaxDurationSeconds,
			&i.Status,
			&i.SamplesTaken,
			&i.ProbesOk,
			&i.ProbesTotal,
			&i.DistinctIps,
			&i.LastSampleAt,
			&i.LastPrimaryIp,
			&i.LastCategory,
			&i.LastRttMs,
			&i.LastError,
			&i.CreatedAt,
			&i.StartedAt,
			&i.StoppedAt,
			&i.SequenceOffset,
			&i.TargetCountry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const stopSession = `-- name: StopSession :execrows
UPDATE sampling_sessions
SET status = 'stopped', stopped_at = $1
WHERE id = $2 AND status = 'running'
`

type StopSessionParams struct {
	StoppedAt pgtype.Timestamptz `json:"stopped_at"`
	ID        uuid.UUID          `json:"id"`
}

func (q *Queries) StopSession(ctx context.Context, arg StopSessionParams) (int64, error) {
	result, err := q.db.Exec(ctx, stopSession, arg.StoppedAt, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateSessionSnapshot = `-- name: UpdateSessionSnapshot :exec
UPDATE sampling_sessions SET
  samples_taken = $1, probes_ok = $2,
  probes_total = $3, distinct_ips = $4,
  last_sample_at = $5,
  last_primary_ip = NULLIF($6::text, '')::inet,
  last_rtt_ms = $7, last_error = NULLIF($8::text, '')
WHERE id = $9
`

type UpdateSessionSnapshotParams struct {
	SamplesTaken  int32              `json:"samples_taken"`
	ProbesOk      int64              `json:"probes_ok"`
	ProbesTotal   int64              `json:"probes_total"`
	DistinctIps   int32              `json:"distinct_ips"`
	LastSampleAt  pgtype.Timestamptz `json:"last_sample_at"`
	LastPrimaryIp string             `json:"last_primary_ip"`
	LastRttMs     *int32             `json:"last_rtt_ms"`
	LastError     string             `json:"last_error"`
	ID            uuid.UUID          `json:"id"`
}

func (q *Queries) UpdateSessionSnapshot(ctx context.Context, arg UpdateSessionSnapshotParams) error {
	_, err := q.db.Exec(ctx, updateSessionSnapshot,
		arg.SamplesTaken,
		arg.ProbesOk,
		arg.ProbesTotal,
		arg.DistinctIps,
		arg.LastSampleAt,
		arg.LastPrimaryIp,
		arg.LastRttMs,
		arg.LastError,
		arg.ID,
	)
	return err
}

const upsertSessionIP = `-- name: UpsertSessionIP :exec
INSERT INTO session_ips (session_id, ip, first_seen, last_seen, hit_count)
VALUES ($1, $2::text::inet, $3, $3, $4)
ON CONFLICT (session_id, ip) DO UPDATE
SET last_seen = EXCLUDED.last_seen, hit_count = session_ips.hit_count + EXCLUDED.hit_count
`

type UpsertSessionIPParams struct {
	SessionID uuid.UUID          `json:"session_id"`
	Ip        string             `json:"ip"`
	SeenAt    pgtype.Timestamptz `json:"seen_at"`
	Hits      int64              `json:"hits"`
}

func (q *Queries) UpsertSessionIP(ctx context.Context, arg UpsertSessionIPParams) error {
	_, err := q.db.Exec(ctx, upsertSessionIP,
		arg.SessionID,
		arg.Ip,
		arg.SeenAt,
		arg.Hits,
	)
	return err
}
